// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP7SDd9_pYE8q0dusT759C1Dv5rfy2F-4',
    appId: '1:924000443081:web:6f79fa98caa5e0167c8b18',
    messagingSenderId: '924000443081',
    projectId: 'flutter-login-1b0c5',
    authDomain: 'flutter-login-1b0c5.firebaseapp.com',
    storageBucket: 'flutter-login-1b0c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPHaU1KFcOiSTEWQ4niR-PpfStCMYVNnI',
    appId: '1:924000443081:android:da304bf9b730da057c8b18',
    messagingSenderId: '924000443081',
    projectId: 'flutter-login-1b0c5',
    storageBucket: 'flutter-login-1b0c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGJ4JKjIw9eCW1nGjozugMEK-50yFnpY',
    appId: '1:924000443081:ios:6323bb5c1a6185017c8b18',
    messagingSenderId: '924000443081',
    projectId: 'flutter-login-1b0c5',
    storageBucket: 'flutter-login-1b0c5.appspot.com',
    iosBundleId: 'com.example.scholarshipApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiGJ4JKjIw9eCW1nGjozugMEK-50yFnpY',
    appId: '1:924000443081:ios:6323bb5c1a6185017c8b18',
    messagingSenderId: '924000443081',
    projectId: 'flutter-login-1b0c5',
    storageBucket: 'flutter-login-1b0c5.appspot.com',
    iosBundleId: 'com.example.scholarshipApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP7SDd9_pYE8q0dusT759C1Dv5rfy2F-4',
    appId: '1:924000443081:web:164baf4352e835f77c8b18',
    messagingSenderId: '924000443081',
    projectId: 'flutter-login-1b0c5',
    authDomain: 'flutter-login-1b0c5.firebaseapp.com',
    storageBucket: 'flutter-login-1b0c5.appspot.com',
  );

}